create table users (
    id       bigint generated by default as identity primary key,
    name     varchar(100)  not null,
    email    varchar(255)  not null,
    password varchar(255)  not null
);

alter table users add constraint uk_users_email unique (email);
